repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs/blob/main
repository: dynamsoft-docs/capture-vision-docs
docFullPath: https://www.dynamsoft.com/capture-vision/docs/core/
firstLevelUrl: /capture-vision/docs/core/
docHomePage: /capture-vision/docs/core/introduction/
searchIndexName: Crawler-DCV-Docs-New
searchNeedFilter: true

dcvb_introduction: /capture-vision/docs/core/introduction/
dcvb_architecture: /capture-vision/docs/core/architecture/
dcvb_parameters: /capture-vision/docs/core/parameters/
dcvb_enums: /capture-vision/docs/core/enums/
dcvb_parameters_reference: /capture-vision/docs/core/parameters/reference/
dcvb_license_activation: /capture-vision/docs/core/license/

dcvb_js: /capture-vision/docs/web/programming/javascript/
dcvb_cpp: /capture-vision/docs/server/programming/cplusplus/
dcvb_dotnet: /capture-vision/docs/server/programming/dotnet/
dcvb_python: /capture-vision/docs/server/programming/python/
dcvb_java: /capture-vision/docs/server/programming/java/
dcvb_android: /capture-vision/docs/mobile/programming/android/
dcvb_ios: /capture-vision/docs/mobile/programming/ios/
dcvb_maui: /capture-vision/docs/mobile/programming/maui/
dcvb_react_native: /capture-vision/docs/mobile/programming/react-native/
dcvb_cordova: /capture-vision/docs/mobile/programming/cordova/
dcvb_flutter: /capture-vision/docs/mobile/programming/flutter/
dcvb_xamarin: /capture-vision/docs/mobile/programming/xamarin/
dcv_archive_react_native: /capture-vision/docs-archive/mobile/programming/react-native/
dcv_archive_flutter: /capture-vision/docs-archive/mobile/programming/flutter/

dlr_archived_introduction: /label-recognition/docs-archive/core/introduction/
ddn_archived_introduction: /document-normalizer/docs-archive/core/introduction/
dcp_archived_introduction: /code-parser/docs-archive/core/introduction/
dce_archived_introduction: /camera-enhancer/docs-archive/core/introduction/


assets: /capture-vision/docs/core/assets/
edit_icon: /capture-vision/docs/core/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/core/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/core/assets/img-icon/icon-dnt.svg

useVersionTree: true
isDCV: true
useJSVersionV3: true

baseurl: "/capture-vision/docs/core"
plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root

