# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu
          [ -d DCVDocCore ] && rm -rf DCVDocCore
          [ -d capture-vision-docs ] && rm -rf capture-vision-docs 
          [ -d Docs-Template-Repo-DCV2 ] && rm -rf Docs-Template-Repo-DCV2
          cd /home/ubuntu

      - name: Build the full site - main
        run: |
          cd /home/ubuntu
          mkdir -p DCVDocCore
          git clone --depth 1 https://github.com/dynamsoft-docs/capture-vision-docs.git capture-vision-docs
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-DCV2
          cp -rfp ./capture-vision-docs/* ./DCVDocCore/
          cp -rfp ./Docs-Template-Repo-DCV2/* ./DCVDocCore/
          cd DCVDocCore && bundle exec jekyll build
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCVDocCore/_site/ ./www.dynamsoft.com/capture-vision/docs/core/ prod
         
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DCVDocCore-preview ] && rm -rf DCVDocCore-preview
          [ -d capture-vision-docs-preview ] && rm -rf capture-vision-docs-preview 
          [ -d Docs-Template-Repo-DCV2-Preview ] && rm -rf Docs-Template-Repo-DCV2-Preview
          cd /home/ubuntu

      - name: Build the full site - preview
        run: |
          cd /home/ubuntu
          mkdir -p DCVDocCore-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/capture-vision-docs.git capture-vision-docs-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-DCV2-Preview
          cp -rfp ./capture-vision-docs-preview/* ./DCVDocCore-preview/
          cp -rfp ./Docs-Template-Repo-DCV2-Preview/* ./DCVDocCore-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCVDocCore-preview/_config.yml
          cd DCVDocCore-preview && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCVDocCore-preview/_site/
          server-dir: /www.dynamsoft.com/capture-vision/docs/core/